import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import IndexContext from "@/context/indexContext";


const instrumentSans = Instrument_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <IndexContext>
        <body className={`${instrumentSans.className} bg-custom_offwhite`}>
          {children}
        </body>
      </IndexContext>
    </html>
  );
}
